// SPDX-License-Identifier: MIT
// Copyright (c) 2026 David Dunnock <dunnoda@gmail.com>
/**
 * Embeds the sample replies in `test-data/thermal-control/` into the bundle.
 *
 * WHY A GENERATOR. §11 rule 7 keeps fixture inputs as data in `test-data/`,
 * and the app also ships them, behind the "Fixture data" badge, until the
 * Tauri client exists. Importing JSON directly would need `resolveJsonModule`,
 * a change to the tsconfig §13.3 fixes, and an import that leaves `src/`,
 * which the `../` ban forbids. So the data is written into a TypeScript module
 * under `src/ipc/generated/`, which Biome skips as generated.
 *
 * THE OUTPUT IS DATA, TYPED `unknown`. It is not a contract type and nothing
 * is checked here: the replies go through the same schema a backend reply
 * does, in `ipc/model-queries.ts`. `src/ipc/fixture-data.test.ts` fails if the
 * generated module and the JSON disagree, so an edit to one without the other
 * cannot pass the gate.
 *
 *     bun run fixtures
 */

import { readdir } from "node:fs/promises";
import path from "node:path";

const root = path.resolve(import.meta.dir, "..");
const source = path.join(root, "test-data/thermal-control");
const target = path.join(root, "src/ipc/generated/thermal-control.ts");

async function readJson(file: string): Promise<unknown> {
  const value: unknown = await Bun.file(file).json();
  return value;
}

const elementsDir = path.join(source, "elements");
const elementFiles = (await readdir(elementsDir)).filter((name) => name.endsWith(".json")).sort();
const elements: Record<string, unknown> = {};
for (const name of elementFiles) {
  elements[name.slice(0, -".json".length)] = await readJson(path.join(elementsDir, name));
}

// files/<workspace path>.json, keyed by the workspace path.
const filesDir = path.join(source, "files");
const fileEntries = (await readdir(filesDir, { recursive: true }))
  .filter((name) => name.endsWith(".json"))
  .map((name) => name.split(path.sep).join("/"))
  .sort();
const files: Record<string, unknown> = {};
for (const name of fileEntries) {
  files[name.slice(0, -".json".length)] = await readJson(path.join(filesDir, name));
}

const replies = {
  workspace: await readJson(path.join(source, "workspace.json")),
  views: await readJson(path.join(source, "views.json")),
  elements,
  files,
};

const module = `// SPDX-License-Identifier: MIT
// Copyright (c) 2026 David Dunnock <dunnoda@gmail.com>
/**
 * GENERATED by tools/embed-fixtures.ts from test-data/thermal-control/.
 * Do not edit: edit the JSON and run \`bun run fixtures\`. See that directory's
 * README for what this data is and is not.
 */

/** The mockup's sample model, as raw replies. Parsed like any backend reply. */
export const THERMAL_CONTROL: Readonly<{
  workspace: unknown;
  views: unknown;
  elements: Readonly<Record<string, unknown>>;
  files: Readonly<Record<string, unknown>>;
}> = ${JSON.stringify(replies, null, 2)};
`;

await Bun.write(target, module);
console.log(
  `wrote ${path.relative(root, target)} (${elementFiles.length} elements, ${fileEntries.length} files)`,
);
