AcceptNode@sysml ::= OccurrenceUsagePrefix AcceptNodeDeclaration ActionBody ;
AcceptNodeDeclaration@sysml ::= ActionNodeUsageDeclaration? 'accept' AcceptParameterPart ;
AcceptParameterPart@sysml ::= PayloadParameterMember ( 'via' NodeParameterMember )? ;
ActionBehaviorMember@sysml ::= BehaviorUsageMember | ActionNodeMember ;
ActionBody@sysml ::= ';' | '{' ActionBodyItem* '}' ;
ActionBodyItem@sysml ::= NonBehaviorBodyItem | InitialNodeMember ActionTargetSuccessionMember* | SourceSuccessionMember? ActionBehaviorMember ActionTargetSuccessionMember* | GuardedSuccessionMember ;
ActionBodyParameter@sysml ::= ( 'action' UsageDeclaration? )? '{' ActionBodyItem* '}' ;
ActionBodyParameterMember@sysml ::= ActionBodyParameter ;
ActionDefinition@sysml ::= OccurrenceDefinitionPrefix 'action' 'def' DefinitionDeclaration ActionBody ;
ActionNode@sysml ::= ControlNode | SendNode | AcceptNode | AssignmentNode | TerminateNode | IfNode | WhileLoopNode | ForLoopNode ;
ActionNodeMember@sysml ::= MemberPrefix ActionNode ;
ActionNodePrefix@sysml ::= OccurrenceUsagePrefix ActionNodeUsageDeclaration? ;
ActionNodeUsageDeclaration@sysml ::= 'action' UsageDeclaration? ;
ActionTargetSuccession@sysml ::= ( TargetSuccession | GuardedTargetSuccession | DefaultTargetSuccession ) UsageBody ;
ActionTargetSuccessionMember@sysml ::= MemberPrefix ActionTargetSuccession ;
ActionUsage@sysml ::= OccurrenceUsagePrefix 'action' ActionUsageDeclaration ActionBody ;
ActionUsageDeclaration@sysml ::= UsageDeclaration ValuePart? ;
ActorMember@sysml ::= MemberPrefix ActorUsage ;
ActorUsage@sysml ::= 'actor' UsageExtensionKeyword* Usage ;
AliasMember ::= MemberPrefix 'alias' ( '<' NAME '>' )? NAME? 'for' QualifiedName RelationshipBody ;
AllocationDefinition@sysml ::= OccurrenceDefinitionPrefix 'allocation' 'def' Definition ;
AllocationUsage@sysml ::= OccurrenceUsagePrefix AllocationUsageDeclaration UsageBody ;
AllocationUsageDeclaration@sysml ::= 'allocation' UsageDeclaration ( 'allocate' ConnectorPart )? | 'allocate' ConnectorPart ;
AnalysisCaseDefinition@sysml ::= OccurrenceDefinitionPrefix 'analysis' 'def' DefinitionDeclaration CaseBody ;
AnalysisCaseUsage@sysml ::= OccurrenceUsagePrefix 'analysis' ConstraintUsageDeclaration CaseBody ;
AnnotatingElement@kerml ::= Comment | Documentation | TextualRepresentation | MetadataFeature ;
AnnotatingElement@sysml ::= Comment | Documentation | TextualRepresentation | MetadataUsage ;
AnnotatingMember@sysml ::= MemberPrefix AnnotatingElement ;
Annotation ::= QualifiedName ;
Argument ::= ArgumentValue ;
ArgumentExpression ::= ArgumentExpressionValue ;
ArgumentExpressionMember ::= ArgumentExpression ;
ArgumentExpressionValue ::= OwnedExpressionReference ;
ArgumentList ::= '(' ( PositionalArgumentList | NamedArgumentList )? ')' ;
ArgumentMember ::= Argument ;
ArgumentValue ::= OwnedExpression ;
AssertConstraintUsage@sysml ::= OccurrenceUsagePrefix 'assert' 'not'? ( OwnedReferenceSubsetting FeatureSpecializationPart? | 'constraint' ConstraintUsageDeclaration ) CalculationBody ;
AssignmentNode@sysml ::= OccurrenceUsagePrefix AssignmentNodeDeclaration ActionBody ;
AssignmentNodeDeclaration@sysml ::= ActionNodeUsageDeclaration? 'assign' AssignmentTargetMember FeatureChainMember ':=' NodeParameterMember ;
AssignmentTargetBinding@sysml ::= NonFeatureChainPrimaryExpression ;
AssignmentTargetMember@sysml ::= AssignmentTargetParameter ;
AssignmentTargetParameter@sysml ::= ( AssignmentTargetBinding '.' )? ;
Association@kerml ::= TypePrefix 'assoc' ClassifierDeclaration TypeBody ;
AssociationStructure@kerml ::= TypePrefix 'assoc' 'struct' ClassifierDeclaration TypeBody ;
AttributeDefinition@sysml ::= DefinitionPrefix 'attribute' 'def' Definition ;
AttributeUsage@sysml ::= UsagePrefix 'attribute' Usage ;
BaseExpression ::= NullExpression | LiteralExpression | FeatureReferenceExpression | MetadataAccessExpression | InvocationExpression | ConstructorExpression | BodyExpression ;
BasicDefinitionPrefix@sysml ::= 'abstract' | 'variation' ;
BasicFeaturePrefix@kerml ::= FeatureDirection? 'derived'? 'abstract'? ( 'composite' | 'portion' )? ( 'var' | 'const' )? ;
BasicUsagePrefix@sysml ::= RefPrefix 'ref'? ;
Behavior@kerml ::= TypePrefix 'behavior' ClassifierDeclaration TypeBody ;
BehaviorUsageElement@sysml ::= ActionUsage | CalculationUsage | StateUsage | ConstraintUsage | RequirementUsage | ConcernUsage | CaseUsage | AnalysisCaseUsage | VerificationCaseUsage | UseCaseUsage | ViewpointUsage | PerformActionUsage | ExhibitStateUsage | IncludeUseCaseUsage | AssertConstraintUsage | SatisfyRequirementUsage ;
BehaviorUsageMember@sysml ::= MemberPrefix BehaviorUsageElement ;
BinaryConnectorDeclaration@kerml ::= ( FeatureDeclaration? 'from' | 'all' 'from'? )? ConnectorEndMember 'to' ConnectorEndMember ;
BinaryConnectorPart@sysml ::= ConnectorEndMember 'to' ConnectorEndMember ;
BinaryInterfacePart@sysml ::= InterfaceEndMember 'to' InterfaceEndMember ;
BinaryOperator ::= '|' | '&' | 'xor' | '..' | '==' | '!=' | '===' | '!==' | '<' | '>' | '<=' | '>=' | '+' | '-' | '*' | '/' | '%' | '^' | '**' ;
BinaryOperatorExpression ::= ArgumentMember BinaryOperator ArgumentMember EmptyResultMember ;
BindingConnector@kerml ::= FeaturePrefix 'binding' BindingConnectorDeclaration TypeBody ;
BindingConnectorAsUsage@sysml ::= UsagePrefix ( 'binding' UsageDeclaration )? 'bind' ConnectorEndMember '=' ConnectorEndMember UsageBody ;
BindingConnectorDeclaration@kerml ::= FeatureDeclaration ( 'of' ConnectorEndMember '=' ConnectorEndMember )? | 'all'? ( 'of'? ConnectorEndMember '=' ConnectorEndMember )? ;
BodyArgument ::= BodyArgumentValue ;
BodyArgumentMember ::= BodyArgument ;
BodyArgumentValue ::= BodyExpression ;
BodyExpression ::= ExpressionBodyMember ;
BooleanExpression@kerml ::= FeaturePrefix 'bool' FeatureDeclaration? ValuePart? FunctionBody ;
BooleanValue ::= 'true' | 'false' ;
BracketExpression ::= PrimaryArgumentMember '[' SequenceExpressionListMember ']' ;
CalculationBody@sysml ::= ';' | '{' CalculationBodyPart '}' ;
CalculationBodyItem@sysml ::= ActionBodyItem | ReturnParameterMember ;
CalculationBodyPart@sysml ::= CalculationBodyItem* ResultExpressionMember? ;
CalculationDefinition@sysml ::= OccurrenceDefinitionPrefix 'calc' 'def' DefinitionDeclaration CalculationBody ;
CalculationUsage@sysml ::= OccurrenceUsagePrefix 'calc' ActionUsageDeclaration CalculationBody ;
CaseBody@sysml ::= ';' | '{' CaseBodyItem* ResultExpressionMember? '}' ;
CaseBodyItem@sysml ::= ActionBodyItem | ReturnParameterMember | SubjectMember | ActorMember | ObjectiveMember ;
CaseDefinition@sysml ::= OccurrenceDefinitionPrefix 'case' 'def' DefinitionDeclaration CaseBody ;
CaseUsage@sysml ::= OccurrenceUsagePrefix 'case' ConstraintUsageDeclaration CaseBody ;
CastOperator ::= 'as' ;
ChainingPart@kerml ::= 'chains' ( OwnedFeatureChaining | FeatureChain ) ;
Class@kerml ::= TypePrefix 'class' ClassifierDeclaration TypeBody ;
ClassificationExpression ::= ArgumentMember? ( ClassificationTestOperator TypeReferenceMember | CastOperator TypeResultMember ) EmptyResultMember ;
ClassificationTestOperator ::= 'istype' | 'hastype' | '@' ;
Classifier@kerml ::= TypePrefix 'classifier' ClassifierDeclaration TypeBody ;
ClassifierDeclaration@kerml ::= 'all'? Identification OwnedMultiplicity? ( SuperclassingPart | ConjugationPart )? TypeRelationshipPart* ;
CollectExpression ::= PrimaryArgumentMember '.' BodyArgumentMember ;
Comment ::= ( 'comment' Identification ( 'about' Annotation ( ',' Annotation )* )? )? ( 'locale' STRING_VALUE )? REGULAR_COMMENT ;
ConcernDefinition@sysml ::= OccurrenceDefinitionPrefix 'concern' 'def' DefinitionDeclaration RequirementBody ;
ConcernUsage@sysml ::= OccurrenceUsagePrefix 'concern' ConstraintUsageDeclaration RequirementBody ;
ConditionalBinaryOperator ::= '??' | 'or' | 'and' | 'implies' ;
ConditionalBinaryOperatorExpression ::= ArgumentMember ConditionalBinaryOperator ArgumentExpressionMember EmptyResultMember ;
ConditionalExpression ::= 'if' ArgumentMember '?' ArgumentExpressionMember 'else' ArgumentExpressionMember EmptyResultMember ;
ConjugatedPortDefinition@sysml ::= PortConjugation ;
ConjugatedPortDefinitionMember@sysml ::= ConjugatedPortDefinition ;
ConjugatedPortTyping@sysml ::= '~' QualifiedName ;
Conjugation@kerml ::= ( 'conjugation' Identification )? 'conjugate' ( QualifiedName | FeatureChain ) ( '~' | 'conjugates' ) ( QualifiedName | FeatureChain ) RelationshipBody ;
ConjugationPart@kerml ::= ( '~' | 'conjugates' ) OwnedConjugation ;
ConnectionDefinition@sysml ::= OccurrenceDefinitionPrefix 'connection' 'def' Definition ;
ConnectionUsage@sysml ::= OccurrenceUsagePrefix ( 'connection' UsageDeclaration ValuePart? ( 'connect' ConnectorPart )? | 'connect' ConnectorPart ) UsageBody ;
Connector@kerml ::= FeaturePrefix 'connector' ( FeatureDeclaration? ValuePart? | ConnectorDeclaration ) TypeBody ;
ConnectorDeclaration@kerml ::= BinaryConnectorDeclaration | NaryConnectorDeclaration ;
ConnectorEnd ::= OwnedCrossMultiplicityMember? ( NAME ( '::>' | 'references' ) )? OwnedReferenceSubsetting ;
ConnectorEndMember ::= ConnectorEnd ;
ConnectorPart@sysml ::= BinaryConnectorPart | NaryConnectorPart ;
ConstraintDefinition@sysml ::= OccurrenceDefinitionPrefix 'constraint' 'def' DefinitionDeclaration CalculationBody ;
ConstraintUsage@sysml ::= OccurrenceUsagePrefix 'constraint' ConstraintUsageDeclaration CalculationBody ;
ConstraintUsageDeclaration@sysml ::= UsageDeclaration ValuePart? ;
ConstructorExpression ::= 'new' InstantiatedTypeMember ConstructorResultMember ;
ConstructorResult ::= ArgumentList ;
ConstructorResultMember ::= ConstructorResult ;
ControlNode@sysml ::= MergeNode | DecisionNode | JoinNode | ForkNode ;
ControlNodePrefix@sysml ::= RefPrefix 'individual'? PortionKind? UsageExtensionKeyword* ;
Crosses ::= ( '=>' | 'crosses' ) OwnedCrossSubsetting ;
DataType@kerml ::= TypePrefix 'datatype' ClassifierDeclaration TypeBody ;
DecisionNode@sysml ::= ControlNodePrefix 'decide' UsageDeclaration ActionBody ;
DefaultInterfaceEnd@sysml ::= 'end' Usage ;
DefaultReferenceUsage@sysml ::= 'end'? RefPrefix ( ( '<' NAME '>' NAME? | NAME ) FeatureSpecializationPart? | FeatureSpecializationPart ) UsageCompletion ;
DefaultTargetSuccession@sysml ::= 'else' TransitionSuccessionMember ;
Definition@sysml ::= DefinitionDeclaration DefinitionBody ;
DefinitionBody@sysml ::= ';' | '{' DefinitionBodyItem* '}' ;
DefinitionBodyItem@sysml ::= DefinitionMember | VariantUsageMember | NonOccurrenceUsageMember | SourceSuccessionMember? OccurrenceUsageMember | AliasMember | Import ;
DefinitionDeclaration@sysml ::= Identification SubclassificationPart? ;
DefinitionElement@sysml ::= Package | LibraryPackage | AnnotatingElement | Dependency | AttributeDefinition | EnumerationDefinition | OccurrenceDefinition | IndividualDefinition | ItemDefinition | PartDefinition | ConnectionDefinition | FlowDefinition | InterfaceDefinition | AllocationDefinition | PortDefinition | ActionDefinition | CalculationDefinition | StateDefinition | ConstraintDefinition | RequirementDefinition | ConcernDefinition | CaseDefinition | AnalysisCaseDefinition | VerificationCaseDefinition | UseCaseDefinition | ViewDefinition | ViewpointDefinition | RenderingDefinition | MetadataDefinition | ExtendedDefinition ;
DefinitionExtensionKeyword@sysml ::= PrefixMetadataMember ;
DefinitionMember@sysml ::= MemberPrefix DefinitionElement ;
DefinitionPrefix@sysml ::= BasicDefinitionPrefix? DefinitionExtensionKeyword* ;
Dependency@kerml ::= PrefixMetadataAnnotation* 'dependency' ( Identification? 'from' )? QualifiedName ( ',' QualifiedName )* 'to' QualifiedName ( ',' QualifiedName )* RelationshipBody ;
Dependency@sysml ::= PrefixMetadataAnnotation* 'dependency' DependencyDeclaration RelationshipBody ;
DependencyDeclaration@sysml ::= ( Identification 'from' )? QualifiedName ( ',' QualifiedName )* 'to' QualifiedName ( ',' QualifiedName )* ;
Differencing@kerml ::= QualifiedName | OwnedFeatureChain ;
DifferencingPart@kerml ::= 'differences' Differencing ( ',' Differencing )* ;
Disjoining@kerml ::= ( 'disjoining' Identification )? 'disjoint' ( QualifiedName | FeatureChain ) 'from' ( QualifiedName | FeatureChain ) RelationshipBody ;
DisjoiningPart@kerml ::= 'disjoint' 'from' OwnedDisjoining ( ',' OwnedDisjoining )* ;
DoActionMember@sysml ::= MemberPrefix 'do' StateActionUsage ;
Documentation ::= 'doc' Identification ( 'locale' STRING_VALUE )? REGULAR_COMMENT ;
EffectBehaviorMember@sysml ::= 'do' EffectBehaviorUsage ;
EffectBehaviorUsage@sysml ::= EmptyActionUsage | TransitionPerformActionUsage | TransitionAcceptActionUsage | TransitionSendActionUsage | TransitionAssignmentActionUsage ;
ElementFilterMember ::= MemberPrefix 'filter' OwnedExpression ';' ;
ElementReferenceMember ::= QualifiedName ;
EmptyActionUsage@sysml ::=  ;
EmptyEndMember@sysml ::= EmptyFeature ;
EmptyFeature ::=  ;
EmptyMultiplicity@sysml ::=  ;
EmptyMultiplicityMember@sysml ::= EmptyMultiplicity ;
EmptyParameterMember@sysml ::= EmptyUsage ;
EmptyResultMember ::= EmptyFeature ;
EmptyUsage@sysml ::=  ;
EndFeaturePrefix@kerml ::= 'const'? 'end' ;
EndUsagePrefix@sysml ::= 'end' OwnedCrossFeatureMember? ;
EntryActionMember@sysml ::= MemberPrefix 'entry' StateActionUsage ;
EntryTransitionMember@sysml ::= MemberPrefix ( GuardedTargetSuccession | 'then' TransitionSuccession ) ';' ;
EnumeratedValue@sysml ::= UsageExtensionKeyword* 'enum'? Usage ;
EnumerationBody@sysml ::= ';' | '{' ( AnnotatingMember | EnumerationUsageMember )* '}' ;
EnumerationDefinition@sysml ::= DefinitionExtensionKeyword* 'enum' 'def' DefinitionDeclaration EnumerationBody ;
EnumerationUsage@sysml ::= UsagePrefix 'enum' Usage ;
EnumerationUsageMember@sysml ::= MemberPrefix EnumeratedValue ;
EventOccurrenceUsage@sysml ::= OccurrenceUsagePrefix 'event' ( OwnedReferenceSubsetting FeatureSpecializationPart? | 'occurrence' UsageDeclaration? ) UsageCompletion ;
ExhibitStateUsage@sysml ::= OccurrenceUsagePrefix 'exhibit' ( OwnedReferenceSubsetting FeatureSpecializationPart? | 'state' UsageDeclaration ) ValuePart? StateUsageBody ;
ExitActionMember@sysml ::= MemberPrefix 'exit' StateActionUsage ;
Expose@sysml ::= 'expose' ( MembershipExpose | NamespaceExpose ) RelationshipBody ;
Expression@kerml ::= FeaturePrefix 'expr' FeatureDeclaration? ValuePart? FunctionBody ;
ExpressionBody@kerml ::= '{' FunctionBodyPart '}' ;
ExpressionBody@sysml ::= CalculationBody ;
ExpressionBodyMember ::= ExpressionBody ;
ExpressionParameterMember@sysml ::= OwnedExpression ;
ExtendedDefinition@sysml ::= BasicDefinitionPrefix? DefinitionExtensionKeyword+ 'def' Definition ;
ExtendedUsage@sysml ::= UnextendedUsagePrefix UsageExtensionKeyword+ Usage ;
ExtentExpression ::= 'all' TypeReferenceMember ;
Feature@kerml ::= ( FeaturePrefix ( 'feature' | PrefixMetadataMember ) FeatureDeclaration? | ( EndFeaturePrefix | BasicFeaturePrefix ) FeatureDeclaration ) ValuePart? TypeBody ;
FeatureBinding@sysml ::= OwnedExpression ;
FeatureChain@kerml ::= OwnedFeatureChaining ( '.' OwnedFeatureChaining )+ ;
FeatureChainExpression ::= NonFeatureChainPrimaryArgumentMember '.' FeatureChainMember ;
FeatureChainMember@kerml ::= FeatureReferenceMember | OwnedFeatureChainMember ;
FeatureChainMember@sysml ::= QualifiedName | OwnedFeatureChainMember ;
FeatureChainPrefix@sysml ::= ( OwnedFeatureChaining '.' )+ OwnedFeatureChaining '.' ;
FeatureDeclaration@kerml ::= 'all'? ( FeatureIdentification ( FeatureSpecializationPart | ConjugationPart )? | FeatureSpecializationPart | ConjugationPart ) FeatureRelationshipPart* ;
FeatureDirection ::= 'in' | 'out' | 'inout' ;
FeatureElement@kerml ::= Feature | Step | Expression | BooleanExpression | Invariant | Connector | BindingConnector | Succession | Flow | SuccessionFlow ;
FeatureIdentification@kerml ::= '<' NAME '>' NAME? | NAME ;
FeatureInverting@kerml ::= ( 'inverting' Identification? )? 'inverse' ( QualifiedName | OwnedFeatureChain ) 'of' ( QualifiedName | OwnedFeatureChain ) RelationshipBody ;
FeatureMember@kerml ::= TypeFeatureMember | OwnedFeatureMember ;
FeaturePrefix@kerml ::= ( EndFeaturePrefix OwnedCrossFeatureMember? | BasicFeaturePrefix ) PrefixMetadataMember* ;
FeatureReference ::= QualifiedName ;
FeatureReferenceExpression ::= FeatureReferenceMember EmptyResultMember ;
FeatureReferenceMember ::= FeatureReference ;
FeatureRelationshipPart@kerml ::= TypeRelationshipPart | ChainingPart | InvertingPart | TypeFeaturingPart ;
FeatureSpecialization ::= Typings | Subsettings | References | Crosses | Redefinitions ;
FeatureSpecializationPart ::= FeatureSpecialization+ MultiplicityPart? FeatureSpecialization* | MultiplicityPart FeatureSpecialization* ;
FeatureTyping@kerml ::= ( 'specialization' Identification )? 'typing' QualifiedName ( ':' | 'typed' 'by' ) GeneralType RelationshipBody ;
FeatureTyping@sysml ::= OwnedFeatureTyping | ConjugatedPortTyping ;
FeatureValue ::= ( '=' | ':=' | 'default' ( '=' | ':=' )? ) OwnedExpression ;
FilterPackage@kerml ::= ImportDeclaration FilterPackageMember+ ;
FilterPackage@sysml ::= FilterPackageImport FilterPackageMember+ ;
FilterPackageImport@sysml ::= ImportDeclaration ;
FilterPackageMember ::= '[' OwnedExpression ']' ;
Flow@kerml ::= FeaturePrefix 'flow' FlowDeclaration TypeBody ;
FlowDeclaration@kerml ::= FeatureDeclaration? ValuePart? ( 'of' PayloadFeatureMember )? ( 'from' FlowEndMember 'to' FlowEndMember )? | 'all'? FlowEndMember 'to' FlowEndMember ;
FlowDeclaration@sysml ::= UsageDeclaration ValuePart? ( 'of' FlowPayloadFeatureMember )? ( 'from' FlowEndMember 'to' FlowEndMember )? | FlowEndMember 'to' FlowEndMember ;
FlowDefinition@sysml ::= OccurrenceDefinitionPrefix 'flow' 'def' Definition ;
FlowEnd@kerml ::= ( OwnedReferenceSubsetting '.' )? FlowFeatureMember ;
FlowEnd@sysml ::= FlowEndSubsetting? FlowFeatureMember ;
FlowEndMember ::= FlowEnd ;
FlowEndSubsetting@sysml ::= QualifiedName '.' | FeatureChainPrefix ;
FlowFeature ::= FlowFeatureRedefinition ;
FlowFeatureMember ::= FlowFeature ;
FlowFeatureRedefinition ::= QualifiedName ;
FlowPayloadFeature@sysml ::= PayloadFeature ;
FlowPayloadFeatureMember@sysml ::= FlowPayloadFeature ;
FlowUsage@sysml ::= OccurrenceUsagePrefix 'flow' FlowDeclaration DefinitionBody ;
ForLoopNode@sysml ::= ActionNodePrefix 'for' ForVariableDeclarationMember 'in' NodeParameterMember ActionBodyParameterMember ;
ForVariableDeclaration@sysml ::= UsageDeclaration ;
ForVariableDeclarationMember@sysml ::= ForVariableDeclaration ;
ForkNode@sysml ::= ControlNodePrefix 'fork' UsageDeclaration ActionBody ;
FramedConcernMember@sysml ::= MemberPrefix? 'frame' FramedConcernUsage ;
FramedConcernUsage@sysml ::= OwnedReferenceSubsetting FeatureSpecializationPart? RequirementBody | ( UsageExtensionKeyword* 'concern' | UsageExtensionKeyword+ ) ConstraintUsageDeclaration RequirementBody ;
Function@kerml ::= TypePrefix 'function' ClassifierDeclaration FunctionBody ;
FunctionBody@kerml ::= ';' | '{' FunctionBodyPart '}' ;
FunctionBodyPart@kerml ::= ( TypeBodyElement | ReturnFeatureMember )* ResultExpressionMember? ;
FunctionOperationExpression ::= PrimaryArgumentMember '->' InstantiatedTypeMember ( BodyArgumentMember | FunctionReferenceArgumentMember | ArgumentList ) EmptyResultMember ;
FunctionReference ::= ReferenceTyping ;
FunctionReferenceArgument ::= FunctionReferenceArgumentValue ;
FunctionReferenceArgumentMember ::= FunctionReferenceArgument ;
FunctionReferenceArgumentValue ::= FunctionReferenceExpression ;
FunctionReferenceExpression ::= FunctionReferenceMember ;
FunctionReferenceMember ::= FunctionReference ;
GeneralType@kerml ::= QualifiedName | OwnedFeatureChain ;
GuardExpressionMember@sysml ::= 'if' OwnedExpression ;
GuardedSuccession@sysml ::= ( 'succession' UsageDeclaration )? 'first' FeatureChainMember GuardExpressionMember 'then' TransitionSuccessionMember UsageBody ;
GuardedSuccessionMember@sysml ::= MemberPrefix GuardedSuccession ;
GuardedTargetSuccession@sysml ::= GuardExpressionMember 'then' TransitionSuccessionMember ;
Identification ::= ( '<' NAME '>' )? NAME? ;
IfNode@sysml ::= ActionNodePrefix 'if' ExpressionParameterMember ActionBodyParameterMember ( 'else' ( ActionBodyParameterMember | IfNodeParameterMember ) )? ;
IfNodeParameterMember@sysml ::= IfNode ;
Import ::= VisibilityIndicator 'import' 'all'? ImportDeclaration RelationshipBody ;
ImportDeclaration ::= MembershipImport | NamespaceImport ;
IncludeUseCaseUsage@sysml ::= OccurrenceUsagePrefix 'include' ( OwnedReferenceSubsetting FeatureSpecializationPart? | 'use' 'case' UsageDeclaration ) ValuePart? CaseBody ;
IndexExpression ::= PrimaryArgumentMember '#' '(' SequenceExpressionListMember ')' ;
IndividualDefinition@sysml ::= BasicDefinitionPrefix? 'individual' DefinitionExtensionKeyword* 'def' Definition EmptyMultiplicityMember ;
IndividualUsage@sysml ::= BasicUsagePrefix 'individual' UsageExtensionKeyword* Usage ;
InitialNodeMember@sysml ::= MemberPrefix 'first' QualifiedName RelationshipBody ;
InstantiatedTypeMember ::= InstantiatedTypeReference | OwnedFeatureChainMember ;
InstantiatedTypeReference ::= QualifiedName ;
Interaction@kerml ::= TypePrefix 'interaction' ClassifierDeclaration TypeBody ;
InterfaceBody@sysml ::= ';' | '{' InterfaceBodyItem* '}' ;
InterfaceBodyItem@sysml ::= DefinitionMember | VariantUsageMember | InterfaceNonOccurrenceUsageMember | SourceSuccessionMember? InterfaceOccurrenceUsageMember | AliasMember | Import ;
InterfaceDefinition@sysml ::= OccurrenceDefinitionPrefix 'interface' 'def' DefinitionDeclaration InterfaceBody ;
InterfaceEnd@sysml ::= OwnedCrossMultiplicityMember? ( NAME ( '::>' | 'references' ) )? OwnedReferenceSubsetting ;
InterfaceEndMember@sysml ::= InterfaceEnd ;
InterfaceNonOccurrenceUsageElement@sysml ::= ReferenceUsage | AttributeUsage | EnumerationUsage | BindingConnectorAsUsage | SuccessionAsUsage ;
InterfaceNonOccurrenceUsageMember@sysml ::= MemberPrefix InterfaceNonOccurrenceUsageElement ;
InterfaceOccurrenceUsageElement@sysml ::= DefaultInterfaceEnd | StructureUsageElement | BehaviorUsageElement ;
InterfaceOccurrenceUsageMember@sysml ::= MemberPrefix InterfaceOccurrenceUsageElement ;
InterfacePart@sysml ::= BinaryInterfacePart | NaryInterfacePart ;
InterfaceUsage@sysml ::= OccurrenceUsagePrefix 'interface' InterfaceUsageDeclaration InterfaceBody ;
InterfaceUsageDeclaration@sysml ::= UsageDeclaration ValuePart? ( 'connect' InterfacePart )? | InterfacePart ;
Intersecting@kerml ::= QualifiedName | OwnedFeatureChain ;
IntersectingPart@kerml ::= 'intersects' Intersecting ( ',' Intersecting )* ;
Invariant@kerml ::= FeaturePrefix 'inv' ( 'true' | 'false' )? FeatureDeclaration? ValuePart? FunctionBody ;
InvertingPart@kerml ::= 'inverse' 'of' OwnedFeatureInverting ;
InvocationExpression ::= InstantiatedTypeMember ArgumentList EmptyResultMember ;
ItemDefinition@sysml ::= OccurrenceDefinitionPrefix 'item' 'def' Definition ;
ItemUsage@sysml ::= OccurrenceUsagePrefix 'item' Usage ;
JoinNode@sysml ::= ControlNodePrefix 'join' UsageDeclaration ActionBody ;
LibraryPackage ::= 'standard'? 'library' PrefixMetadataMember* PackageDeclaration PackageBody ;
LiteralBoolean ::= BooleanValue ;
LiteralExpression ::= LiteralBoolean | LiteralString | LiteralInteger | LiteralReal | LiteralInfinity ;
LiteralInfinity ::= '*' ;
LiteralInteger ::= DECIMAL_VALUE ;
LiteralReal ::= RealValue ;
LiteralString ::= STRING_VALUE ;
MemberElement@kerml ::= AnnotatingElement | NonFeatureElement ;
MemberPrefix ::= VisibilityIndicator? ;
MembershipExpose@sysml ::= MembershipImport ;
MembershipImport ::= QualifiedName ( '::' '**' )? ;
MergeNode@sysml ::= ControlNodePrefix 'merge' UsageDeclaration ActionBody ;
Message@sysml ::= OccurrenceUsagePrefix 'message' MessageDeclaration DefinitionBody ;
MessageDeclaration@sysml ::= UsageDeclaration ValuePart? ( 'of' FlowPayloadFeatureMember )? ( 'from' MessageEventMember 'to' MessageEventMember )? | MessageEventMember 'to' MessageEventMember ;
MessageEvent@sysml ::= OwnedReferenceSubsetting ;
MessageEventMember@sysml ::= MessageEvent ;
MetaCastOperator ::= 'meta' ;
Metaclass@kerml ::= TypePrefix 'metaclass' ClassifierDeclaration TypeBody ;
MetaclassificationExpression ::= MetadataArgumentMember ( MetaclassificationTestOperator TypeReferenceMember | MetaCastOperator TypeResultMember ) EmptyResultMember ;
MetaclassificationTestOperator ::= '@@' ;
MetadataAccessExpression ::= ElementReferenceMember '.' 'metadata' ;
MetadataArgument ::= MetadataValue ;
MetadataArgumentMember ::= MetadataArgument ;
MetadataBody@kerml ::= ';' | '{' MetadataBodyElement* '}' ;
MetadataBody@sysml ::= ';' | '{' ( DefinitionMember | MetadataBodyUsageMember | AliasMember | Import )* '}' ;
MetadataBodyElement@kerml ::= NonFeatureMember | MetadataBodyFeatureMember | AliasMember | Import ;
MetadataBodyFeature@kerml ::= 'feature'? ( ':>>' | 'redefines' )? OwnedRedefinition FeatureSpecializationPart? ValuePart? MetadataBody ;
MetadataBodyFeatureMember@kerml ::= MetadataBodyFeature ;
MetadataBodyUsage@sysml ::= 'ref'? ( ':>>' | 'redefines' )? OwnedRedefinition FeatureSpecializationPart? ValuePart? MetadataBody ;
MetadataBodyUsageMember@sysml ::= MetadataBodyUsage ;
MetadataDefinition@sysml ::= 'abstract'? DefinitionExtensionKeyword* 'metadata' 'def' Definition ;
MetadataFeature@kerml ::= PrefixMetadataMember* ( '@' | 'metadata' ) MetadataFeatureDeclaration ( 'about' Annotation ( ',' Annotation )* )? MetadataBody ;
MetadataFeatureDeclaration@kerml ::= ( Identification ( ':' | 'typed' 'by' ) )? OwnedFeatureTyping ;
MetadataReference ::= ElementReferenceMember ;
MetadataUsage@sysml ::= UsageExtensionKeyword* ( '@' | 'metadata' ) MetadataUsageDeclaration ( 'about' Annotation ( ',' Annotation )* )? MetadataBody ;
MetadataUsageDeclaration@sysml ::= ( Identification ( ':' | 'defined' 'by' ) )? OwnedFeatureTyping ;
MetadataValue ::= MetadataReference ;
Multiplicity@kerml ::= MultiplicitySubset | MultiplicityRange ;
MultiplicityBounds@kerml ::= '[' ( MultiplicityExpressionMember '..' )? MultiplicityExpressionMember ']' ;
MultiplicityExpressionMember ::= LiteralExpression | FeatureReferenceExpression ;
MultiplicityPart ::= OwnedMultiplicity | OwnedMultiplicity? ( 'ordered' 'nonunique'? | 'nonunique' 'ordered'? ) ;
MultiplicityRange@kerml ::= 'multiplicity' Identification MultiplicityBounds TypeBody ;
MultiplicityRange@sysml ::= '[' ( MultiplicityExpressionMember '..' )? MultiplicityExpressionMember ']' ;
MultiplicitySubset@kerml ::= 'multiplicity' Identification Subsets TypeBody ;
NamedArgument ::= ParameterRedefinition '=' ArgumentValue ;
NamedArgumentList ::= NamedArgumentMember ( ',' NamedArgumentMember )* ;
NamedArgumentMember ::= NamedArgument ;
Namespace@kerml ::= PrefixMetadataMember* NamespaceDeclaration NamespaceBody ;
NamespaceBody@kerml ::= ';' | '{' NamespaceBodyElement* '}' ;
NamespaceBodyElement@kerml ::= NamespaceMember | AliasMember | Import ;
NamespaceDeclaration@kerml ::= 'namespace' Identification ;
NamespaceExpose@sysml ::= NamespaceImport ;
NamespaceFeatureMember@kerml ::= MemberPrefix FeatureElement ;
NamespaceImport ::= QualifiedName '::' '*' ( '::' '**' )? | FilterPackage ;
NamespaceMember@kerml ::= NonFeatureMember | NamespaceFeatureMember ;
NaryConnectorDeclaration@kerml ::= FeatureDeclaration? '(' ConnectorEndMember ',' ConnectorEndMember ( ',' ConnectorEndMember )* ')' ;
NaryConnectorPart@sysml ::= '(' ConnectorEndMember ',' ConnectorEndMember ( ',' ConnectorEndMember )* ')' ;
NaryInterfacePart@sysml ::= '(' InterfaceEndMember ',' InterfaceEndMember ( ',' InterfaceEndMember )* ')' ;
NodeParameter@sysml ::= FeatureBinding ;
NodeParameterMember@sysml ::= NodeParameter ;
NonBehaviorBodyItem@sysml ::= Import | AliasMember | DefinitionMember | VariantUsageMember | NonOccurrenceUsageMember | SourceSuccessionMember? StructureUsageMember ;
NonFeatureChainPrimaryArgument@kerml ::= NonFeatureChainPrimaryArgumentValue ;
NonFeatureChainPrimaryArgumentMember ::= PrimaryArgument ;
NonFeatureChainPrimaryArgumentValue@kerml ::= NonFeatureChainPrimaryExpression ;
NonFeatureChainPrimaryExpression ::= BracketExpression | IndexExpression | SequenceExpression | SelectExpression | CollectExpression | FunctionOperationExpression | BaseExpression ;
NonFeatureElement@kerml ::= Dependency | Namespace | Type | Classifier | DataType | Class | Structure | Metaclass | Association | AssociationStructure | Interaction | Behavior | Function | Predicate | Multiplicity | Package | LibraryPackage | Specialization | Conjugation | Subclassification | Disjoining | FeatureInverting | FeatureTyping | Subsetting | Redefinition | TypeFeaturing ;
NonFeatureMember@kerml ::= MemberPrefix MemberElement ;
NonOccurrenceUsageElement@sysml ::= DefaultReferenceUsage | ReferenceUsage | AttributeUsage | EnumerationUsage | BindingConnectorAsUsage | SuccessionAsUsage | ExtendedUsage ;
NonOccurrenceUsageMember@sysml ::= MemberPrefix NonOccurrenceUsageElement ;
NullExpression ::= 'null' | '(' ')' ;
ObjectiveMember@sysml ::= MemberPrefix 'objective' ObjectiveRequirementUsage ;
ObjectiveRequirementUsage@sysml ::= UsageExtensionKeyword* ConstraintUsageDeclaration RequirementBody ;
OccurrenceDefinition@sysml ::= OccurrenceDefinitionPrefix 'occurrence' 'def' Definition ;
OccurrenceDefinitionPrefix@sysml ::= BasicDefinitionPrefix? ( 'individual' EmptyMultiplicityMember )? DefinitionExtensionKeyword* ;
OccurrenceUsage@sysml ::= OccurrenceUsagePrefix 'occurrence' Usage ;
OccurrenceUsageElement@sysml ::= StructureUsageElement | BehaviorUsageElement ;
OccurrenceUsageMember@sysml ::= MemberPrefix OccurrenceUsageElement ;
OccurrenceUsagePrefix@sysml ::= ( EndUsagePrefix | BasicUsagePrefix 'individual'? PortionKind? ) UsageExtensionKeyword* ;
OwnedAnnotation ::= AnnotatingElement ;
OwnedConjugation@kerml ::= QualifiedName | FeatureChain ;
OwnedCrossFeature@kerml ::= BasicFeaturePrefix FeatureDeclaration ;
OwnedCrossFeature@sysml ::= BasicUsagePrefix UsageDeclaration ;
OwnedCrossFeatureMember ::= OwnedCrossFeature ;
OwnedCrossMultiplicity ::= OwnedMultiplicity ;
OwnedCrossMultiplicityMember ::= OwnedCrossMultiplicity ;
OwnedCrossSubsetting@kerml ::= GeneralType ;
OwnedCrossSubsetting@sysml ::= QualifiedName | OwnedFeatureChain ;
OwnedDisjoining@kerml ::= QualifiedName | FeatureChain ;
OwnedExpression ::= ConditionalExpression | ConditionalBinaryOperatorExpression | BinaryOperatorExpression | UnaryOperatorExpression | ClassificationExpression | MetaclassificationExpression | ExtentExpression | PrimaryExpression ;
OwnedExpressionMember ::= OwnedExpression ;
OwnedExpressionReference ::= OwnedExpressionMember ;
OwnedExpressionReferenceMember@kerml ::= OwnedExpressionReference ;
OwnedFeatureChain@kerml ::= FeatureChain ;
OwnedFeatureChain@sysml ::= OwnedFeatureChaining ( '.' OwnedFeatureChaining )+ ;
OwnedFeatureChainMember@kerml ::= FeatureChain ;
OwnedFeatureChainMember@sysml ::= OwnedFeatureChain ;
OwnedFeatureChaining ::= QualifiedName ;
OwnedFeatureInverting@kerml ::= QualifiedName | OwnedFeatureChain ;
OwnedFeatureMember@kerml ::= MemberPrefix FeatureElement ;
OwnedFeatureTyping@kerml ::= GeneralType ;
OwnedFeatureTyping@sysml ::= QualifiedName | OwnedFeatureChain ;
OwnedMultiplicity@kerml ::= OwnedMultiplicityRange ;
OwnedMultiplicity@sysml ::= MultiplicityRange ;
OwnedMultiplicityRange@kerml ::= MultiplicityBounds ;
OwnedRedefinition@kerml ::= GeneralType ;
OwnedRedefinition@sysml ::= QualifiedName | OwnedFeatureChain ;
OwnedReferenceSubsetting@kerml ::= GeneralType ;
OwnedReferenceSubsetting@sysml ::= QualifiedName | OwnedFeatureChain ;
OwnedRelatedElement@kerml ::= NonFeatureElement | FeatureElement ;
OwnedSpecialization@kerml ::= GeneralType ;
OwnedSubclassification ::= QualifiedName ;
OwnedSubsetting@kerml ::= GeneralType ;
OwnedSubsetting@sysml ::= QualifiedName | OwnedFeatureChain ;
OwnedTypeFeaturing@kerml ::= QualifiedName ;
Package ::= PrefixMetadataMember* PackageDeclaration PackageBody ;
PackageBody@kerml ::= ';' | '{' ( NamespaceBodyElement | ElementFilterMember )* '}' ;
PackageBody@sysml ::= ';' | '{' PackageBodyElement* '}' ;
PackageBodyElement@sysml ::= PackageMember | ElementFilterMember | AliasMember | Import ;
PackageDeclaration ::= 'package' Identification ;
PackageMember@sysml ::= MemberPrefix ( DefinitionElement | UsageElement ) ;
ParameterRedefinition ::= QualifiedName ;
PartDefinition@sysml ::= OccurrenceDefinitionPrefix 'part' 'def' Definition ;
PartUsage@sysml ::= OccurrenceUsagePrefix 'part' Usage ;
PayloadFeature@kerml ::= Identification PayloadFeatureSpecializationPart ValuePart? | Identification ValuePart | OwnedFeatureTyping OwnedMultiplicity? | OwnedMultiplicity OwnedFeatureTyping ;
PayloadFeature@sysml ::= Identification? PayloadFeatureSpecializationPart ValuePart? | OwnedFeatureTyping OwnedMultiplicity? | OwnedMultiplicity OwnedFeatureTyping ;
PayloadFeatureMember@kerml ::= PayloadFeature ;
PayloadFeatureSpecializationPart ::= FeatureSpecialization+ MultiplicityPart? FeatureSpecialization* | MultiplicityPart FeatureSpecialization+ ;
PayloadParameter@sysml ::= PayloadFeature | Identification PayloadFeatureSpecializationPart? TriggerValuePart ;
PayloadParameterMember@sysml ::= PayloadParameter ;
PerformActionUsage@sysml ::= OccurrenceUsagePrefix 'perform' PerformActionUsageDeclaration ActionBody ;
PerformActionUsageDeclaration@sysml ::= ( OwnedReferenceSubsetting FeatureSpecializationPart? | 'action' UsageDeclaration ) ValuePart? ;
PortConjugation@sysml ::=  ;
PortDefinition@sysml ::= DefinitionPrefix 'port' 'def' Definition ConjugatedPortDefinitionMember ;
PortUsage@sysml ::= OccurrenceUsagePrefix 'port' Usage ;
PortionKind@sysml ::= 'snapshot' | 'timeslice' ;
PortionUsage@sysml ::= BasicUsagePrefix 'individual'? PortionKind UsageExtensionKeyword* Usage ;
PositionalArgumentList ::= ArgumentMember ( ',' ArgumentMember )* ;
Predicate@kerml ::= TypePrefix 'predicate' ClassifierDeclaration FunctionBody ;
PrefixMetadataAnnotation@kerml ::= '#' PrefixMetadataFeature ;
PrefixMetadataAnnotation@sysml ::= '#' PrefixMetadataUsage ;
PrefixMetadataFeature@kerml ::= OwnedFeatureTyping ;
PrefixMetadataMember@kerml ::= '#' PrefixMetadataFeature ;
PrefixMetadataMember@sysml ::= '#' PrefixMetadataUsage ;
PrefixMetadataUsage@sysml ::= OwnedFeatureTyping ;
PrimaryArgument ::= PrimaryArgumentValue ;
PrimaryArgumentMember ::= PrimaryArgument ;
PrimaryArgumentValue ::= PrimaryExpression ;
PrimaryExpression ::= FeatureChainExpression | NonFeatureChainPrimaryExpression ;
QualifiedName ::= ( '$' '::' )? ( NAME '::' )* NAME ;
RealValue ::= DECIMAL_VALUE? '.' ( DECIMAL_VALUE | EXPONENTIAL_VALUE ) | EXPONENTIAL_VALUE ;
Redefines ::= ( ':>>' | 'redefines' ) OwnedRedefinition ;
Redefinition@kerml ::= ( 'specialization' Identification )? 'redefinition' SpecificType ( ':>>' | 'redefines' ) GeneralType RelationshipBody ;
Redefinitions ::= Redefines ( ',' OwnedRedefinition )* ;
RefPrefix@sysml ::= FeatureDirection? 'derived'? ( 'abstract' | 'variation' )? 'constant'? ;
ReferenceTyping ::= QualifiedName ;
ReferenceUsage@sysml ::= ( EndUsagePrefix | RefPrefix ) 'ref' Usage ;
References ::= ( '::>' | 'references' ) OwnedReferenceSubsetting ;
RelationshipBody@kerml ::= ';' | '{' RelationshipOwnedElement* '}' ;
RelationshipBody@sysml ::= ';' | '{' OwnedAnnotation* '}' ;
RelationshipOwnedElement@kerml ::= OwnedRelatedElement | OwnedAnnotation ;
RenderingDefinition@sysml ::= OccurrenceDefinitionPrefix 'rendering' 'def' Definition ;
RenderingUsage@sysml ::= OccurrenceUsagePrefix 'rendering' Usage ;
RequirementBody@sysml ::= ';' | '{' RequirementBodyItem* '}' ;
RequirementBodyItem@sysml ::= DefinitionBodyItem | SubjectMember | RequirementConstraintMember | FramedConcernMember | RequirementVerificationMember | ActorMember | StakeholderMember ;
RequirementConstraintMember@sysml ::= MemberPrefix? RequirementKind RequirementConstraintUsage ;
RequirementConstraintUsage@sysml ::= OwnedReferenceSubsetting FeatureSpecializationPart? RequirementBody | ( UsageExtensionKeyword* 'constraint' | UsageExtensionKeyword+ ) ConstraintUsageDeclaration CalculationBody ;
RequirementDefinition@sysml ::= OccurrenceDefinitionPrefix 'requirement' 'def' DefinitionDeclaration RequirementBody ;
RequirementKind@sysml ::= 'assume' | 'require' ;
RequirementUsage@sysml ::= OccurrenceUsagePrefix 'requirement' ConstraintUsageDeclaration RequirementBody ;
RequirementVerificationMember@sysml ::= MemberPrefix 'verify' RequirementVerificationUsage ;
RequirementVerificationUsage@sysml ::= OwnedReferenceSubsetting FeatureSpecialization* RequirementBody | ( UsageExtensionKeyword* 'requirement' | UsageExtensionKeyword+ ) ConstraintUsageDeclaration RequirementBody ;
ResultExpressionMember@kerml ::= MemberPrefix OwnedExpression ;
ResultExpressionMember@sysml ::= MemberPrefix? OwnedExpression ;
ReturnFeatureMember@kerml ::= MemberPrefix 'return' FeatureElement ;
ReturnParameterMember@sysml ::= MemberPrefix? 'return' UsageElement ;
RootNamespace@kerml ::= NamespaceBodyElement* ;
RootNamespace@sysml ::= PackageBodyElement* ;
SatisfactionFeatureValue@sysml ::= SatisfactionReferenceExpression ;
SatisfactionParameter@sysml ::= SatisfactionFeatureValue ;
SatisfactionReferenceExpression@sysml ::= FeatureChainMember ;
SatisfactionSubjectMember@sysml ::= SatisfactionParameter ;
SatisfyRequirementUsage@sysml ::= OccurrenceUsagePrefix 'assert'? 'not'? 'satisfy' ( OwnedReferenceSubsetting FeatureSpecializationPart? | 'requirement' UsageDeclaration ) ValuePart? ( 'by' SatisfactionSubjectMember )? RequirementBody ;
SelectExpression ::= PrimaryArgumentMember '.?' BodyArgumentMember ;
SendNode@sysml ::= OccurrenceUsagePrefix ActionNodeUsageDeclaration? 'send' ( NodeParameterMember SenderReceiverPart? | EmptyParameterMember SenderReceiverPart )? ActionBody ;
SendNodeDeclaration@sysml ::= ActionNodeUsageDeclaration? 'send' NodeParameterMember SenderReceiverPart? ;
SenderReceiverPart@sysml ::= 'via' NodeParameterMember ( 'to' NodeParameterMember )? | EmptyParameterMember 'to' NodeParameterMember ;
SequenceExpression ::= '(' SequenceExpressionList ')' ;
SequenceExpressionList ::= OwnedExpression ','? | SequenceOperatorExpression ;
SequenceExpressionListMember ::= SequenceExpressionList ;
SequenceOperatorExpression ::= OwnedExpressionMember ',' SequenceExpressionListMember ;
SourceEnd@sysml ::= OwnedMultiplicity? ;
SourceEndMember@sysml ::= SourceEnd ;
SourceSuccession@sysml ::= SourceEndMember ;
SourceSuccessionMember@sysml ::= 'then' SourceSuccession ;
Specialization@kerml ::= ( 'specialization' Identification )? 'subtype' SpecificType ( ':>' | 'specializes' ) GeneralType RelationshipBody ;
SpecializationPart@kerml ::= ( ':>' | 'specializes' ) OwnedSpecialization ( ',' OwnedSpecialization )* ;
SpecificType@kerml ::= QualifiedName | OwnedFeatureChain ;
StakeholderMember@sysml ::= MemberPrefix StakeholderUsage ;
StakeholderUsage@sysml ::= 'stakeholder' UsageExtensionKeyword* Usage ;
StateAcceptActionUsage@sysml ::= AcceptNodeDeclaration ActionBody ;
StateActionUsage@sysml ::= EmptyActionUsage ';' | StatePerformActionUsage | StateAcceptActionUsage | StateSendActionUsage | StateAssignmentActionUsage ;
StateAssignmentActionUsage@sysml ::= AssignmentNodeDeclaration ActionBody ;
StateBodyItem@sysml ::= NonBehaviorBodyItem | SourceSuccessionMember? BehaviorUsageMember TargetTransitionUsageMember* | TransitionUsageMember | EntryActionMember EntryTransitionMember* | DoActionMember | ExitActionMember ;
StateDefBody@sysml ::= ';' | 'parallel'? '{' StateBodyItem* '}' ;
StateDefinition@sysml ::= OccurrenceDefinitionPrefix 'state' 'def' DefinitionDeclaration StateDefBody ;
StatePerformActionUsage@sysml ::= PerformActionUsageDeclaration ActionBody ;
StateSendActionUsage@sysml ::= SendNodeDeclaration ActionBody ;
StateUsage@sysml ::= OccurrenceUsagePrefix 'state' ActionUsageDeclaration StateUsageBody ;
StateUsageBody@sysml ::= ';' | 'parallel'? '{' StateBodyItem* '}' ;
Step@kerml ::= FeaturePrefix 'step' FeatureDeclaration? ValuePart? TypeBody ;
Structure@kerml ::= TypePrefix 'struct' ClassifierDeclaration TypeBody ;
StructureUsageElement@sysml ::= OccurrenceUsage | IndividualUsage | PortionUsage | EventOccurrenceUsage | ItemUsage | PartUsage | ViewUsage | RenderingUsage | PortUsage | ConnectionUsage | InterfaceUsage | AllocationUsage | Message | FlowUsage | SuccessionFlowUsage ;
StructureUsageMember@sysml ::= MemberPrefix StructureUsageElement ;
Subclassification@kerml ::= ( 'specialization' Identification )? 'subclassifier' QualifiedName ( ':>' | 'specializes' ) QualifiedName RelationshipBody ;
SubclassificationPart@sysml ::= ( ':>' | 'specializes' ) OwnedSubclassification ( ',' OwnedSubclassification )* ;
SubjectMember@sysml ::= MemberPrefix SubjectUsage ;
SubjectUsage@sysml ::= 'subject' UsageExtensionKeyword* Usage ;
Subsets ::= ( ':>' | 'subsets' ) OwnedSubsetting ;
Subsetting@kerml ::= ( 'specialization' Identification )? 'subset' SpecificType ( ':>' | 'subsets' ) GeneralType RelationshipBody ;
Subsettings ::= Subsets ( ',' OwnedSubsetting )* ;
Succession@kerml ::= FeaturePrefix 'succession' SuccessionDeclaration TypeBody ;
SuccessionAsUsage@sysml ::= UsagePrefix ( 'succession' UsageDeclaration )? 'first' ConnectorEndMember 'then' ConnectorEndMember UsageBody ;
SuccessionDeclaration@kerml ::= FeatureDeclaration ( 'first' ConnectorEndMember 'then' ConnectorEndMember )? | 'all'? ( 'first'? ConnectorEndMember 'then' ConnectorEndMember )? ;
SuccessionFlow@kerml ::= FeaturePrefix 'succession' 'flow' FlowDeclaration TypeBody ;
SuccessionFlowUsage@sysml ::= OccurrenceUsagePrefix 'succession' 'flow' FlowDeclaration DefinitionBody ;
SuperclassingPart@kerml ::= ( ':>' | 'specializes' ) OwnedSubclassification ( ',' OwnedSubclassification )* ;
TargetSuccession@sysml ::= SourceEndMember 'then' ConnectorEndMember ;
TargetTransitionUsage@sysml ::= EmptyParameterMember ( 'transition' ( EmptyParameterMember TriggerActionMember )? GuardExpressionMember? EffectBehaviorMember? | EmptyParameterMember TriggerActionMember GuardExpressionMember? EffectBehaviorMember? | GuardExpressionMember EffectBehaviorMember? )? 'then' TransitionSuccessionMember ActionBody ;
TargetTransitionUsageMember@sysml ::= MemberPrefix TargetTransitionUsage ;
TerminateNode@sysml ::= OccurrenceUsagePrefix ActionNodeUsageDeclaration? 'terminate' NodeParameterMember? ActionBody ;
TextualRepresentation ::= ( 'rep' Identification )? 'language' STRING_VALUE REGULAR_COMMENT ;
TransitionAcceptActionUsage@sysml ::= AcceptNodeDeclaration ( '{' ActionBodyItem* '}' )? ;
TransitionAssignmentActionUsage@sysml ::= AssignmentNodeDeclaration ( '{' ActionBodyItem* '}' )? ;
TransitionPerformActionUsage@sysml ::= PerformActionUsageDeclaration ( '{' ActionBodyItem* '}' )? ;
TransitionSendActionUsage@sysml ::= SendNodeDeclaration ( '{' ActionBodyItem* '}' )? ;
TransitionSuccession@sysml ::= EmptyEndMember ConnectorEndMember ;
TransitionSuccessionMember@sysml ::= TransitionSuccession ;
TransitionUsage@sysml ::= 'transition' ( UsageDeclaration 'first' )? FeatureChainMember EmptyParameterMember ( EmptyParameterMember TriggerActionMember )? GuardExpressionMember? EffectBehaviorMember? 'then' TransitionSuccessionMember ActionBody ;
TransitionUsageMember@sysml ::= MemberPrefix TransitionUsage ;
TriggerAction@sysml ::= AcceptParameterPart ;
TriggerActionMember@sysml ::= 'accept' TriggerAction ;
TriggerExpression@sysml ::= ( 'at' | 'after' ) ArgumentMember | 'when' ArgumentExpressionMember ;
TriggerFeatureValue@sysml ::= TriggerExpression ;
TriggerValuePart@sysml ::= TriggerFeatureValue ;
Type@kerml ::= TypePrefix 'type' TypeDeclaration TypeBody ;
TypeBody@kerml ::= ';' | '{' TypeBodyElement* '}' ;
TypeBodyElement@kerml ::= NonFeatureMember | FeatureMember | AliasMember | Import ;
TypeDeclaration@kerml ::= 'all'? Identification OwnedMultiplicity? ( SpecializationPart | ConjugationPart )+ TypeRelationshipPart* ;
TypeFeatureMember@kerml ::= MemberPrefix 'member' FeatureElement ;
TypeFeaturing@kerml ::= 'featuring' ( Identification 'of' )? QualifiedName 'by' QualifiedName RelationshipBody ;
TypeFeaturingPart@kerml ::= 'featured' 'by' OwnedTypeFeaturing ( ',' OwnedTypeFeaturing )* ;
TypePrefix@kerml ::= 'abstract'? PrefixMetadataMember* ;
TypeReference ::= ReferenceTyping ;
TypeReferenceMember ::= TypeReference ;
TypeRelationshipPart@kerml ::= DisjoiningPart | UnioningPart | IntersectingPart | DifferencingPart ;
TypeResultMember ::= TypeReference ;
TypedBy@kerml ::= ( ':' | 'typed' 'by' ) OwnedFeatureTyping ;
TypedBy@sysml ::= ( ':' | 'defined' 'by' ) FeatureTyping ;
Typings@kerml ::= TypedBy ( ',' OwnedFeatureTyping )* ;
Typings@sysml ::= TypedBy ( ',' FeatureTyping )* ;
UnaryOperator ::= '+' | '-' | '~' | 'not' ;
UnaryOperatorExpression ::= UnaryOperator ArgumentMember EmptyResultMember ;
UnextendedUsagePrefix@sysml ::= EndUsagePrefix | BasicUsagePrefix ;
Unioning@kerml ::= QualifiedName | OwnedFeatureChain ;
UnioningPart@kerml ::= 'unions' Unioning ( ',' Unioning )* ;
Usage@sysml ::= UsageDeclaration UsageCompletion ;
UsageBody@sysml ::= DefinitionBody ;
UsageCompletion@sysml ::= ValuePart? UsageBody ;
UsageDeclaration@sysml ::= Identification FeatureSpecializationPart? ;
UsageElement@sysml ::= NonOccurrenceUsageElement | OccurrenceUsageElement ;
UsageExtensionKeyword@sysml ::= PrefixMetadataMember ;
UsagePrefix@sysml ::= UnextendedUsagePrefix UsageExtensionKeyword* ;
UseCaseDefinition@sysml ::= OccurrenceDefinitionPrefix 'use' 'case' 'def' DefinitionDeclaration CaseBody ;
UseCaseUsage@sysml ::= OccurrenceUsagePrefix 'use' 'case' ConstraintUsageDeclaration CaseBody ;
ValuePart ::= FeatureValue ;
VariantReference@sysml ::= OwnedReferenceSubsetting FeatureSpecialization* UsageBody ;
VariantUsageElement@sysml ::= VariantReference | ReferenceUsage | AttributeUsage | BindingConnectorAsUsage | SuccessionAsUsage | OccurrenceUsage | IndividualUsage | PortionUsage | EventOccurrenceUsage | ItemUsage | PartUsage | ViewUsage | RenderingUsage | PortUsage | ConnectionUsage | InterfaceUsage | AllocationUsage | Message | FlowUsage | SuccessionFlowUsage | BehaviorUsageElement ;
VariantUsageMember@sysml ::= MemberPrefix 'variant' VariantUsageElement ;
VerificationCaseDefinition@sysml ::= OccurrenceDefinitionPrefix 'verification' 'def' DefinitionDeclaration CaseBody ;
VerificationCaseUsage@sysml ::= OccurrenceUsagePrefix 'verification' ConstraintUsageDeclaration CaseBody ;
ViewBody@sysml ::= ';' | '{' ViewBodyItem* '}' ;
ViewBodyItem@sysml ::= DefinitionBodyItem | ElementFilterMember | ViewRenderingMember | Expose ;
ViewDefinition@sysml ::= OccurrenceDefinitionPrefix 'view' 'def' DefinitionDeclaration ViewDefinitionBody ;
ViewDefinitionBody@sysml ::= ';' | '{' ViewDefinitionBodyItem* '}' ;
ViewDefinitionBodyItem@sysml ::= DefinitionBodyItem | ElementFilterMember | ViewRenderingMember ;
ViewRenderingMember@sysml ::= MemberPrefix 'render' ViewRenderingUsage ;
ViewRenderingUsage@sysml ::= OwnedReferenceSubsetting FeatureSpecializationPart? UsageBody | ( UsageExtensionKeyword* 'rendering' | UsageExtensionKeyword+ ) Usage ;
ViewUsage@sysml ::= OccurrenceUsagePrefix 'view' UsageDeclaration? ValuePart? ViewBody ;
ViewpointDefinition@sysml ::= OccurrenceDefinitionPrefix 'viewpoint' 'def' DefinitionDeclaration RequirementBody ;
ViewpointUsage@sysml ::= OccurrenceUsagePrefix 'viewpoint' ConstraintUsageDeclaration RequirementBody ;
VisibilityIndicator ::= 'public' | 'private' | 'protected' ;
WhileLoopNode@sysml ::= ActionNodePrefix ( 'while' ExpressionParameterMember | 'loop' EmptyParameterMember ) ActionBodyParameterMember ( 'until' ExpressionParameterMember ';' )? ;
